import { StyleSheet } from 'react-native';
import { RFValue } from 'react-native-responsive-fontsize';
import {
  COLORS,
  IS_IOS,
  WINDOW_HEIGHT,
  WINDOW_WIDTH,
} from '../../constants/Constants';

export const styles = StyleSheet.create({
  text: {
    color: COLORS.text,
    lineHeight: 14,
    letterSpacing: 0.75,
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
  },
  buttonText: {
    color: COLORS.whiteText,
    lineHeight: 17,
    letterSpacing: 0.75,
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
  },
  blackBackgroundColor: {
    backgroundColor: '#000',
  },
  authViewContainer: {
    width: WINDOW_WIDTH * 0.85,
    alignSelf: 'center',
  },
  horizontalContent: {
    flexDirection: 'row',
  },
  containerMargin: {
    margin: WINDOW_WIDTH * 0.02,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  containerPadding: {
    padding: WINDOW_WIDTH * 0.02,
  },
  logoHeader: {
    width: WINDOW_WIDTH * 0.7,
    alignSelf: 'center',
    marginTop: WINDOW_HEIGHT * 0.03,
  },
  logo: {
    marginVertical: WINDOW_HEIGHT * 0.05,
    width: WINDOW_WIDTH * 0.5,
    height: WINDOW_WIDTH * 0.5,
    alignSelf: 'center',
  },
  avatar: {
    marginBottom: WINDOW_HEIGHT * 0.05,
    backgroundColor: COLORS.raspberry,
    borderRadius: WINDOW_WIDTH * 0.25,
    alignSelf: 'center',
    width: WINDOW_WIDTH * 0.5,
    height: WINDOW_WIDTH * 0.5,
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  avatarEdit: {
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.black,
    borderRadius: WINDOW_WIDTH * 0.06,
    width: WINDOW_WIDTH * 0.12,
    height: WINDOW_WIDTH * 0.12,
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  logsInputLabel: {
    fontSize: RFValue(14),
    marginBottom: WINDOW_WIDTH * 0.01,
    marginLeft: WINDOW_WIDTH * 0.01,
    color: COLORS.black,
  },
  stayConnected: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: WINDOW_WIDTH * 0.02,
  },
  stayConnectedText: {
    fontSize: WINDOW_WIDTH * 0.05,
    color: COLORS.black,
    fontWeight: 'bold',
    marginRight: WINDOW_WIDTH * 0.01,
  },
  menuItemView: {
    width: WINDOW_WIDTH * 0.12,
    height: WINDOW_WIDTH * 0.12,
    borderRadius: WINDOW_WIDTH * 0.06,
    backgroundColor: COLORS.raspberry,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: 2.75,
    color: COLORS.primaryColor,
    fontFamily: 'Poppins-Bold',
  },
  logButtons: {
    width: WINDOW_WIDTH * 0.8,
    borderRadius: 50,
    backgroundColor: COLORS.primaryColor,
    padding: IS_IOS ? RFValue(14) : WINDOW_WIDTH * 0.03,
    alignSelf: 'center',
    justifyContent: 'center',
    // Shadow
    shadowOpacity: 0.3,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowColor: '#000',
    elevation: 4,
  },
  logInputs: {
    width: WINDOW_WIDTH * 0.8,
    borderColor: COLORS.inputBorderColor,
    borderWidth: 2,
    borderRadius: 40,
    backgroundColor: COLORS.lightGrey,
    alignItems: 'center',
    alignSelf: 'center',
  },
  logInputText: {
    flex: 1,
    lineHeight: 14,
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    color: COLORS.inputTextColor,
    padding: RFValue(14),
    paddingLeft: 24,
  },
  logTexts: {
    fontSize: RFValue(14),
    fontWeight: 'bold',
    color: '#000',
  },
  userTypeButton: {
    marginTop: 24,
    width: WINDOW_WIDTH * 0.8,
    padding: RFValue(14),
    alignSelf: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.primaryColor,
    borderRadius: 50,
  },
  userTypeTextButton: {
    fontSize: 14,
    fontFamily: 'Poppins-Medium',
    color: COLORS.primaryColor,
    textAlign: 'center',
  },
  inputAddress: {
    backgroundColor: '#dddddd',
    color: '#000',
    fontSize: RFValue(14),
    fontWeight: 'bold',
    alignSelf: 'center',
    width: WINDOW_WIDTH * 0.7,
  },
  shadowContainer: {
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 5,
    },
  },
  startButton: {
    flexDirection: 'row',
    borderColor: COLORS.peach,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: '#ddd',
    justifyContent: 'space-between',
    width: WINDOW_WIDTH * 0.5,
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  drawer: {
    backgroundColor: '#fff',
    width: WINDOW_WIDTH * 0.7,
  },
  drawerCustomItem: {
    padding: WINDOW_WIDTH * 0.05,
  },
  drawerCustomItemText: {
    color: COLORS.blackBackground,
    fontSize: IS_IOS ? WINDOW_WIDTH * 0.07 : WINDOW_WIDTH * 0.05,
    fontWeight: 'bold',
  },
  drawerIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    marginTop: 8,
    padding: 8,
  },
  checkpointCardView: {
    backgroundColor: '#fff',
    borderRadius: 15,
    width: WINDOW_WIDTH * 0.8,
  },
  deconnectionView: {
    backgroundColor: COLORS.peach,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: WINDOW_WIDTH * 0.07,
    paddingHorizontal: WINDOW_WIDTH * 0.02,
  },
  disabled: {
    backgroundColor: COLORS.blackBackground,
    opacity: 0.3,
    borderColor: 'transparent',
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
});
